### ISSUE TITLE
Login UI Glitch

### ISSUE THREAD

**Issue by qsecnet** [s0t7x/decky-sunshine#10]
While using the plugin, there are instances where the UI prompts for re-login even after successfully logging in with correct credentials. 

![image](https://github.com/s0t7x/decky-sunshine/assets/165438494/fd292e5d-67d5-4c2a-b090-0bf0fe9201ff)

Upon encountering this issue, reopening the plugin resolves it, but attempting to log in again presents a login page with a blank password field and lacking back or cancel options. This poses a risk, especially for non-superusers, as accidental clicks on the login button could erase saved credentials.

Additionally, considering the workflow, it would be beneficial to include an option to toggle the autostart functionality for the sunshine server upon boot.

#### Steps to Reproduce:
1. Log in with correct credentials.
2. Encounter UI prompting for re-login.
3. Observe the blank password field and missing navigation options on the login page.

#### Expected Behavior:
1. Seamless login experience without encountering repeated login prompts.
2. Clear navigation options and filled password field on the login page.

#### Suggestions:
1. Implement a fix for the login UI glitch to prevent repeated login prompts.
2. Add back or cancel options on the login page to avoid accidental credential erasure.

**Comment by s0t7x** [comment]
I'm aware of the issue where the UI occasionally prompts for re-login, even after successfully logging in with the correct credentials. Currently, the cause of this behavior is unclear, and I'm investigating it further. Although it's not critical, I understand it affects the user experience. Given i'm not used to react, it may take some time to resolve, but please know that it's on my radar. Thank you for your patience and understanding as I work to improve the plugin.
