### ISSUE TITLE
Autostart Option

### ISSUE THREAD

**Issue by qsecnet** [s0t7x/decky-sunshine#11]
It would be beneficial to include an option to toggle an autostart functionality for the sunshine server upon boot.
This would drastically enhance the user experience.

**Comment by s0t7x** [comment]
Absolutely, I completely agree with you on the importance of adding an option to toggle the autostart functionality for the sunshine server upon boot. This feature would indeed greatly enhance the user experience, providing users with more control over the server's startup behavior.

Thank you for bringing up this suggestion—it's an excellent addition to my roadmap.

**Comment by s0th1s** [comment]
Brilliant idea, I second this enhancement request!  When I am on the go and using my phone to remote in  on my steam deck to check for updates, it is super annoying to reboot and lose connectivity until I can toggle the decky sunshine back on at home.

Looking forward to this enhancement hopefully soon.

Thanks for the hardwork!!

**Comment by s0th1s** [comment]
I would also like to add it would be nice if there was a remember username check box for the login on the decky sunshine app.  This way we don't have to delete the default "decky_sunshine" username everytime we have to login again.  

Cheers!

**Comment by chris-chin** [comment]
> I would also like to add it would be nice if there was a remember username check box for the login on the decky sunshine app. This way we don't have to delete the default "decky_sunshine" username everytime we have to login again.
> 
> Cheers!

I just changed the username in Sunshine to decky-sunshine.

Gret work on this plugin. I am awaiting the AutoStart functionality eagerly.

**Comment by s0t7x** [comment]
The plugin now saves the last enabled state. After a reboot it should return to that state. Please give it a try. I really felt the immediate need for it when restarting remotely...
