### ISSUE TITLE
Publish to the Plugin Store 

### ISSUE THREAD

**Issue by stavfx** [s0t7x/decky-sunshine#13]
More people need access to this incredible tool
Please publish it to the official plugin store.

**Comment by stavfx** [comment]
(I am aware you probably want to complete some other tasks before it's "production ready". Opening this issue as a trackable roadmap item)

**Comment by s0t7x** [comment]
Hey @stavfx,
I made a Pull Request to the store database about 2 weeks ago. 
[https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/592](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/592)

Let's hope they gonna merge it soon ;)

**Comment by stavfx** [comment]
Oh awesome! Didn't realize 😅

**Comment by s0t7x** [comment]
Published on testing AND prod/live store
