### ISSUE TITLE
No description for people, who are not used to Streaming

### ISSUE THREAD

**Issue by Baronischwasser** [s0t7x/decky-sunshine#2]
I asked my girlfriend if she wants to stream but she don't know how to use anything

**Comment by s0t7x** [comment]
**Thanks for your feedback!**
I strive for an out-of-the-box experience for all users including those who aren't familier with sunshine or game streaming at all.

I wll finish implementing the main features and then absolutely take your feedback into consideraton when refactoring the front-end.

**My absolute Goal is:**

- Go into Decky Shop
- Find and install Decky Sunshine
- Enable Sunshine in the Decky Sunshine Sidebar
- Get walked through initial setup and pairing processes
- Start Moonlight Client on any other device and enjoy!

**Comment by s0t7x** [comment]
With release 0.2 i implemented an auto-install of sunshine. You're also able to skip sunshine setup and pair devices directly from quick access now.
I consider this delivering a better ux.

I am curious what else suggestions you have regarding the "girlfriend"-problem. Would an extended README fit?
