### ISSUE TITLE
Infinite load in game mode

### ISSUE THREAD

**Issue by Jaxsown** [s0t7x/decky-sunshine#31]
In desktop mode, Steam Big Picture, the plugin works. In game mode, in 3.1, there is infinite loading. In 4.1, I can turn on the toggle, but then there is infinite loading.

**Comment by Jaxsown** [comment]
I wiped the Decky configuration and reinstalled it. After that, it worked fine in 3.1.

**Comment by Abisco** [comment]
@Jaxsown what does wiping decky configuration mean here?

**Comment by Jaxsown** [comment]
> @Jaxsown what does wiping decky configuration mean here?

Run the decky script in desktop mode you will have an option to "wipe decky loader"
