### ISSUE TITLE
Not on decky store

### ISSUE THREAD

**Issue by PringlePot** [s0t7x/decky-sunshine#41]
Hello,
I would like to use this amazing plugin, but it seems to have been removed from the decky plugin store

**Comment by Jester2262** [comment]
Same here.

**Comment by creeperita09** [comment]
just download the zip from the releases tab, enable developer mode on decky and install it using the install button in decky's developer menu

**Comment by s0t7x** [comment]
https://github.com/s0t7x/decky-sunshine/blob/main/docs/manual_install.md
