### ISSUE TITLE
Sunshine no longer showing in Decky plugin store?

### ISSUE THREAD

**Issue by emmawinston** [s0t7x/decky-sunshine#42]
Hello! This project looks like exactly what I am looking for (trying to get the Steam Deck to work as a host in order to stream a game to a Mac which won't run natively on that Mac), but after installing the Decky store...Decky Sunshine is not there. 

Is there a plan to bring it back?

**Comment by SasakiSadako** [comment]
Same here. Sunshine stopped working yesterday for an unknown reason (never had issues before) so I uninstalled decky-sunshine and tried to reinstall. But as said, it's not on the Decky Pluginstore anymore

**Comment by s0t7x** [comment]
> Here are instructions https://github.com/s0t7x/decky-sunshine/blob/main/docs/manual_install.md
> 
> The plugin seems instable with the latest updates and i can not actively maintain this. Thats why its not in store anymore.

Like stated in #41 

There is a plan to bring it back.
